GET http://localhost:3334/users

###

GET http://localhost:3334/api/users/id/1

###

GET http://localhost:3334/api/users/id/2

###


GET http://localhost:3334/api/users/all

###


POST http://localhost:3334/api/users/create/
Content-Type: application/json

{   

    
    "firstName": "Malcom",
    "lastName": "X",
    "email": "malcomx@noi.org",
    "hashedPassword" : "$2b$12$AMBAW0BvXfFT6xuCyZ1Mm.RvufODuXkIEyoVIXYSqkDCTlCUzRSw2"
}


###


POST http://localhost:3334/api/users/createUser/
Content-Type: application/json

{   

    
    "firstName": "Louis",
    "lastName": "Farrakhan",
    "email": "louisfarrkahan@noi.org",
    "hashedPassword" : "$2b$12$AMBAW0BvXfFT6xuCyZ1Mm.RvufODuXkIEyoVIXYSqkDCTlCUzRSw2"
}


###


POST http://localhost:3334/api/users/createUser/
Content-Type: application/json

{   

    
    "firstName": 1234,
    "lastName": "testLastName",
    "email": 4455545,
    "hashedPassword" : "$2b$12$AMBAW0BvXfFT6xuCyZ1Mm.RvufODuXkIEyoVIXYSqkDCTlCUzRSw2"
}

###


PUT http://localhost:3334/api/users/updateUser/1
Content-Type: application/json

{   
    "firstName": "Anna",
    "lastName": "Carter",
    "email": "loyaltyisbetter@gmail.com",
    "hashedPassword" : "$2b$12$AMBAW0BvXfFT6xuCyZ1Mm.RvufODuXkIEyoVIXYSqkDCTlCUzRSw2"
}

###

PUT http://localhost:3334/api/users/updateUser/1
Content-Type: application/json

{   
    "firstName": "Marvin",
    "lastName": "Carter",
    "email": "oldcat1959@gmail.com",
    "hashedPassword" : "$2b$12$AMBAW0BvXfFT6xuCyZ1Mm.RvufODuXkIEyoVIXYSqkDCTlCUzRSw2"
}

###


GET http://localhost:3334/users/1


###

POST http://localhost:3334/users-create/
Content-Type: application/json

{   

    
    "firstName": "Frank",
    "lastName": "White",
    "email": "fwhite@gmail.com",
    "hashedPassword" : "$2b$12$AMBAW0BvXfFT6xuCyZ1Mm.RvufODuXkIEyoVIXYSqkDCTlCUzRSw2"
}

###


POST http://localhost:3334/users-create/
Content-Type: application/json

{   

    
    "firstName": "John",
    "lastName": "Doe",
    "email": "johndoe@gmail.com",
    "hashedPassword" : "$2b$12$AMBAW0BvXfFT6xuCyZ1Mm.RvufODuXkIEyoVIXYSqkDCTlCUzRSw2"
}
###


POST http://localhost:3334/users-create/
Content-Type: application/json

{   

    
    "firstName": "Jane",
    "lastName": "Doe",
    "email": "janedoe@gmail.com",
    "hashedPassword" : "$2b$12$AMBAW0BvXfFT6xuCyZ1Mm.RvufODuXkIEyoVIXYSqkDCTlCUzRSw2"
}


###



DELETE http://localhost:3334/users-delete-uuid/7a3c1269-ebca-4cdb-bbb2-4dfd8732f265
Content-Type: application/json


###

