export const businesses = [
    {
        id: 0,
        uuid: "22a5da83-94de-4f7f-9370-5f2ae2c0e5b3",
        token: "c8FHiCkUtlTC5Kx5GU1a",
        title: "Wakanda Tours",
        description: "",
        imageSrc: "http://localhost:3334/uploaded/businessphotos/2024/03/23/businessPhoto-1711169127833.webp",
        imagesMultiSrc: null,
        category: "Tours",
        hasStore: 1,
        hasProducts: 1,
        hasServices: 1,
        userId: 1,
        countryId: 3,
        countryCityId: 4,
        countryStateRegionId: 5,
        listingId: 1,
        streetAddress: "4568 Wakanda Blvd",
        streetAddress2: "Bldg 452",
        streetCity: "Accra",
        streetZipCode: "G-46546",
        createdAt: new Date(),
        updatedAt: new Date(),
        isAFranchise: false,
        isTheFranchiseParent: false,
        ownsOtherBusinesses: false
    },
];
