export const users = [
    {
        id: 1,
        uuid: "rpo6fy1d-65na-48ee-9f9d-7ncm0fta3bdc",
        name: "Maureo Carter",
        firstName: "Maureo",
        lastName: "Carter",
        email: "maureocarter@gmail.com",
        image: "",
        phone: "+19048023837",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$AneafNv7kkiVLsyLITXnUe.JWip9/74TyUaaotcJhZ2vZVAS96mSS",
    },
    {
        id: 2,
        uuid: "vd6d84fc-df84-4db9-a104-2b60bb296ea1",
        name: "Martin Carter",
        firstName: "Standard",
        lastName: "Administrator",
        email: "martincarter504@yahoo.com",
        image: "",
        phone: "+12405996770",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 3,
        uuid: "jd6d84fc-df84-4db9-a104-2b60bb296ea1",
        name: "Benjamin Carter",
        firstName: "Benjamin",
        lastName: "Carter",
        email: "webgoonie@gmail.com",
        image: "",
        phone: "+14043227197",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 4,
        uuid: "gk6d84fc-df84-4db9-a104-2b60bb296ea1",
        name: "Harriet Otubea",
        firstName: "Harriet",
        lastName: "Otubea",
        email: "harrietotu653@outlook.com",
        image: "",
        phone: "+233504571655",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 5,
        uuid: "bd6d84fc-df84-4db9-a104-2b60bb296ea1",
        name: "Reeds Redemptor",
        firstName: "Benjamin",
        lastName: "Carter",
        email: "redempterjohn20@gmail.com",
        image: "",
        phone: "+254758251456",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 6,
        uuid: "ad6d84fc-df84-4db9-a104-2b60bb296ea1",
        name: "Caroline Mbondo",
        firstName: "Caroline",
        lastName: "Mbondo",
        email: "carolinembondo60@gmail.com",
        image: "",
        phone: "+254798160029",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 7,
        uuid: "id6d84fc-df84-4db9-a104-2b60bb296ea1",
        name: "Bret Oreta",
        firstName: "Bret",
        lastName: "Oreta",
        email: "bretoreta@gmail.com",
        image: "",
        phone: "+254740821859",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 8,
        uuid: "od6d84fc-df84-4db9-a104-2b60bb296ea1",
        name: "Timothy Kelvin",
        firstName: "Timothy",
        lastName: "Kelvin",
        email: "johndoe@email.com",
        image: "",
        phone: "+254704321761",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 9,
        uuid: "wd6d83fc-d384-4db9-a104-2b60bb296ea1",
        name: "Bobby Genkins",
        firstName: "Bobby ",
        lastName: "Genkins",
        email: "bobby.jenkins@blerditmsp.com",
        image: "",
        phone: "+12298812614 ",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 10,
        uuid: "sd6d84fc-df84-4d69-a104-2b60bb296ea1",
        name: "Yaw Pare",
        firstName: "Yawe",
        lastName: "Pare",
        email: "yawpare@gmail.com",
        image: "",
        phone: "+233234238401",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 11,
        uuid: "qd6d84fc-df84-4db9-a104-2t60bb296ea1",
        name: "Jamaal Bolder",
        firstName: "Jamaal",
        lastName: "Bolder",
        email: "jcbolder@gmail.com",
        image: "",
        phone: "+14042461715",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 12,
        uuid: "cd6rrrfc-df84-4db9-a104-2b60bb246ea1",
        name: "Dennis Matovu",
        firstName: "Dennis",
        lastName: "Matovu",
        email: "dennis.matovu@gmail.com",
        image: "",
        phone: "+16788029934",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 13,
        uuid: "pd6d84fc-df84-4db9-a104-2b60bb296ea0",
        name: "Patrick Keorin",
        firstName: "Patrick",
        lastName: "Keorin",
        email: "patrickkeorin@gmail.com",
        image: "",
        phone: "+13476783024",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 14,
        uuid: "ld6d84fc-df84-4db9-a104-2b60bb296ea2",
        name: "Harvey Hardy",
        firstName: "Harvey",
        lastName: "Hardy",
        email: "hlhardy44@gmail.com",
        image: "",
        phone: "+16014707861",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 15,
        uuid: "fg5684fc-df84-4db9-a104-2b60bb296ea2",
        name: "Faith Carter",
        firstName: "Faith",
        lastName: "Carter",
        email: "faith.k.carter@gmail.com",
        image: "",
        phone: "+14049491170",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 16,
        uuid: "e459909a-5c7a-47b3-999e-e2f1e08a4633",
        name: "Tijani Ibra",
        firstName: "Tijani",
        lastName: "Ibra",
        email: "tijani.ibra@gmail.com",
        image: "",
        phone: "+14126368861",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 17,
        uuid: "02484748-e021-451c-8c72-7ea6f0c34f8d",
        name: "Philip  Kirby",
        firstName: "Philip",
        lastName: "Kirby",
        email: "honestanddependable@gmail.com",
        image: "",
        phone: "+16787325968",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$qAoH25FaNFFw59ZKSsihFOBASrsScPgCgOGuMr9FCqUkGGMESvngm",
    },
    {
        id: 18,
        uuid: "b8acba7c-5ba8-4f6d-8d1c-cc390529c8fe",
        name: "Franca Embassy",
        firstName: "Franca",
        lastName: "Ampomah",
        email: "francaampomah973@gmail.com",
        image: "",
        phone: "+233242756237",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 19,
        uuid: "357043cd-05d0-4cca-8e96-e3c70200b38f",
        name: "Mabel Gbedemah",
        firstName: "Franca",
        lastName: "Embassy",
        email: "mabel.gbedemah@cliftonghana.com",
        image: "",
        phone: "+233 24 275 6237",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
];
