export const users = [
    {
        id: 1,
        uuid: "rpo6fy1d-65na-48ee-9f9d-7ncm0fta3bdc",
        name: "Maureo Carter",
        firstName: "Maureo",
        lastName: "Carter",
        email: "maureocarter@gmail.com",
        image: "",
        phone: "+1 904 802-3837",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$AneafNv7kkiVLsyLITXnUe.JWip9/74TyUaaotcJhZ2vZVAS96mSS",
    },
    {
        id: 2,
        uuid: "vd6d84fc-df84-4db9-a104-2b60bb296ea1",
        name: "Martin Carter",
        firstName: "Standard",
        lastName: "Administrator",
        email: "martincarter504@yahoo.com",
        image: "",
        phone: "+1 (770) 866-6735",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 3,
        uuid: "jd6d84fc-df84-4db9-a104-2b60bb296ea1",
        name: "Benjamin Carter",
        firstName: "Benjamin",
        lastName: "Carter",
        email: "webgoonie@gmail.com",
        image: "",
        phone: "+1 (404) 322-7197",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 4,
        uuid: "gk6d84fc-df84-4db9-a104-2b60bb296ea1",
        name: "Harriet Otubea",
        firstName: "Harriet",
        lastName: "Otubea",
        email: "harrietotu653@outlook.com",
        image: "",
        phone: "+233 50 457 1655",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 5,
        uuid: "bd6d84fc-df84-4db9-a104-2b60bb296ea1",
        name: "Reeds Redemptor",
        firstName: "Benjamin",
        lastName: "Carter",
        email: "redemptorjohn@gmail.com",
        image: "",
        phone: "+254 758 251456",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 6,
        uuid: "ad6d84fc-df84-4db9-a104-2b60bb296ea1",
        name: "Caroline Mbondo",
        firstName: "Caroline",
        lastName: "Mbondo",
        email: "carolinembondo60@gmail.com",
        image: "",
        phone: "+254798160029",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 7,
        uuid: "id6d84fc-df84-4db9-a104-2b60bb296ea1",
        name: "Bret Oreta",
        firstName: "Bret",
        lastName: "Oreta",
        email: "bretoreta@gmail.com",
        image: "",
        phone: "+254 740 821859",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 8,
        uuid: "od6d84fc-df84-4db9-a104-2b60bb296ea1",
        name: "Timothy Kelvin",
        firstName: "Timothy",
        lastName: "Kelvin",
        email: "janedoe@email.com",
        image: "",
        phone: "+254 704 321761",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 9,
        uuid: "wd6d83fc-d384-4db9-a104-2b60bb296ea1",
        name: "Bobby Genkins",
        firstName: "Bobby ",
        lastName: "Genkins",
        email: "bobby.jenkins@blerditmsp.com",
        image: "",
        phone: "+1 (404) 322-7197",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 10,
        uuid: "sd6d84fc-df84-4d69-a104-2b60bb296ea1",
        name: "Yaw Pare",
        firstName: "Yawe",
        lastName: "Pare",
        email: "janedoe@email.com",
        image: "",
        phone: "+233 23 423 8401",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 11,
        uuid: "qd6d84fc-df84-4db9-a104-2t60bb296ea1",
        name: "Jamaal Bolder",
        firstName: "Jamaal",
        lastName: "Bolder",
        email: "jcbolder@gmail.com",
        image: "",
        phone: "+1 404 246 1715",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 12,
        uuid: "cd6rrrfc-df84-4db9-a104-2b60bb246ea1",
        name: "Dennis Matovu",
        firstName: "Dennis",
        lastName: "Matovu",
        email: "dennis.matovu@gmail.com",
        image: "",
        phone: "+1 678 802 9934",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 13,
        uuid: "pd6d84fc-df84-4db9-a104-2b60bb296ea0",
        name: "Patrick Keorin",
        firstName: "Patrick",
        lastName: "Keorin",
        email: "janedoe@email.com",
        image: "",
        phone: "+1 (404) 322-7197",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 14,
        uuid: "ld6d84fc-df84-4db9-a104-2b60bb296ea2",
        name: "Harvey Hardy",
        firstName: "Harvey",
        lastName: "Hardy",
        email: "harvey_hardy@yahoo.com",
        image: "",
        phone: "+1 601 322-7197",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
    {
        id: 14,
        uuid: "fg5684fc-df84-4db9-a104-2b60bb296ea2",
        name: "Faith Carter",
        firstName: "Faith",
        lastName: "Carter",
        email: "faith.k.carter@gmail.com",
        image: "",
        phone: "+1 404 949 1170",
        role: "both",
        emailVerified: new Date(),
        hashedPassword: "$2b$12$kI.rtHYnatU2cqsZMK8BZuNjQ3bPpfqUxi7O0d.I/JWZYz7uSpldu",
    },
];
