




###

GET http://localhost:3334/api/businesses/allbusinesses



###



###

POST http://localhost:3334/api/businesses/createBusinesses
Content-Type: application/json

{
    "listingId": 0,
    "category": "Shopping",
    "countryCity": null,
    "country": null,
    "countryStateRegion": null,
    "cityinfo": null,
    "isAFranchise": null,
    "isTheFranchiseParent": null,
    "ownsOtherBusinesses": null,
    "exactBusinessGeoLocation": [],
    "hasStore": 1,
    "hasProducts": 1,
    "hasServices": 1,
    "imageSrc": [],
    "streetAddress": "",
    "streetAddress2": "",
    "streetCity": "",
    "streetZipCode": "",
    "token": "29L7sIZLRmS9aZyABJll",
    "userId": 2,
    "description": "",
    "title": "",
    "businessId": 0
}



###
###

POST http://localhost:3334/api/businesses/autoSaveBusinessData
Content-Type: application/json

{
    "listingId": 0,
    "category": "Shopping",
    "countryCity": null,
    "country": null,
    "countryStateRegion": null,
    "cityinfo": null,
    "isAFranchise": null,
    "isTheFranchiseParent": null,
    "ownsOtherBusinesses": null,
    "exactBusinessGeoLocation": [],
    "hasStore": 1,
    "hasProducts": 1,
    "hasServices": 1,
    "imageSrc": [],
    "streetAddress": "",
    "streetAddress2": "",
    "streetCity": "",
    "streetZipCode": "",
    "token": "29L7sIZLRmS9aZyABJll",
    "userId": 2,
    "description": "",
    "title": "",
    "businessId": 0
}



###


GET http://localhost:3334/api/businesses/allbusinesses

###

POST http://localhost:3334/api/businesses/createbusinessphotos

Content-Type: application/json

{
    "listingId": 0,
    "category": "Shopping",
    "countryCity": null,
    "country": null,
    "countryStateRegion": null,
    "cityinfo": null,
    "isAFranchise": null,
    "isTheFranchiseParent": null,
    "ownsOtherBusinesses": null,
    "exactBusinessGeoLocation": [],
    "hasStore": 1,
    "hasProducts": 1,
    "hasServices": 1,
    "imageSrc": [],
    "streetAddress": "",
    "streetAddress2": "",
    "streetCity": "",
    "streetZipCode": "",
    "token": "29L7sIZLRmS9aZyABJll",
    "userId": 2,
    "description": "",
    "title": "",
    "businessId": 0
}


###


GET http://localhost:3334/api/businesses/id/1



###

 
GET http://localhost:3334/api/businesses/uuid/5e311e20-942d-4dd8-847f-9e692af01574
//GET http://localhost:3334/api/businesses/uuid/22a5da83-94de-4f7f-9370-5f2ae2c0e5b3

###