
###

GET http://localhost:3334/api/listings/allProperties


###


GET http://localhost:3334/api/listings/propertyuuid/8d33c643-4eda-4fd2-913a-1cad3598d666

###


GET http://localhost:3334/api/listings/uuid/8d33c643-4eda-4fd2-913a-1cad3598d666

###

GET http://localhost:3334/api/listings/allBusinesses


###

POST http://localhost:3334/api/upload
Content-Type: application/json

{
    "email": "webgoonie@gmail.com",
    "hashedPassword": "$2b$12$AMBAW0BvXfFT6xuCyZ1Mm.RvufODuXkIEyoVIXYSqkDCTlCUzRSw2"
}

###

POST http://localhost:3334/api/admins/loginadmin
Content-Type: application/json

{
    "email": "webgoonie@gmail.com",
    "hashedPassword": "$2b$12$AMBAW0BvXfFT6xuCyZ1Mm.RvufODuXkIEyoVIXYSqkDCTlCUzRSw2"
}

###

POST http://localhost:3334/api/listings/createpropertyphotos
Content-Type: application/json

{
    "url1": "webgoonie@gmail.com",
    "url2": "$2b$12$AMBAW0BvXfFT6xuCyZ1Mm.RvufODuXkIEyoVIXYSqkDCTlCUzRSw2"
}



###