
###

GET http://localhost:3334/api/propertys/allproperties


###
###

GET http://localhost:3334/api/propertys/reservationsAtProperty/23d2197b-630d-4863-aeea-827a7500f85d



###
###

GET http://localhost:3334/api/propertys/reservationAtpropertyByUuid/23d2197b-630d-4863-aeea-827a7500f85d



###
###

GET http://localhost:3334/api/propertys/reservationAtpropertyByUuid/fc982479-372e-41a3-804a-d51cbbf8ab6a



###
###

GET http://localhost:3334/api/propertys/reservationsproperty/fc982479-372e-41a3-804a-d51cbbf8ab6a



###

###

POST http://localhost:3334/api/propertys/reservations/create
Content-Type: application/json

{

    "totalPrice": 108.49,
    "startDate": "2024-03-26T04:35:45.015Z",
    "endDate": "2024-03-29T04:35:45.015Z",
    "listingId": 6,
    "propertyUuid": "401d0976-ee08-4648-b5c5-ddbc3324ae6f",
    "userId": 2


}

###


POST http://localhost:3334/api/propertys/reservations/create
Content-Type: application/json

{

    "totalPrice": 78.54,
    "startDate": "2024-03-25T04:35:45.015Z",
    "endDate": "2024-03-25T04:35:45.015Z",
    "listingId": 6,
    "propertyUuid": "401d0976-ee08-4648-b5c5-ddbc3324ae6f",
    "userId": 1


}

###

POST http://localhost:3334/api/propertys/createProperty
Content-Type: application/json

{
    "bathroomCount": 1,
    "category": "Luxury",
    "cityinfo": {
        "value": "Accra",
        "label": "Accra",
        "countryCode": "GH",
        "latlng": [
            "5.55602000",
            "-0.19690000"
        ],
        "latitude": "5.55602000",
        "longitude": "-0.19690000",
        "name": "Accra"
    },
    "description": "Fully Furnished Apartment",
    "guestCount": 4,
    "imageSrc": [],
    "localinfo": {
        "value": "AA",
        "label": "Greater Accra",
        "countryCode": "GH",
        "latlng": [
            "5.81428360",
            "0.07467670"
        ],
        "latitude": "5.81428360",
        "longitude": "0.07467670",
        "name": "Greater Accra",
        "isoCode": "AA"
    },
    "location": {
        "value": "GH",
        "label": "Ghana",
        "currency": "GHS",
        "phonecode": "233",
        "flag": "🇬🇭",
        "latlng": [
            8,
            -2
        ],
        "latitude": 8,
        "longitude": -2,
        "region": "Ghana",
        "isoCode": "GH",
        "name": "Ghana",
        "timezones": []
    },
    "price": "63.58",
    "roomCount": 2,
    "streetAddress": "Third Circular Road",
    "streetAddress2": null,
    "streetCity": "Accra",
    "streetZipCode": "GA-51042",
    "title": "Embassy Gardens",
    "town": null,
    "userId": 1
}



###
###

POST http://localhost:3334/api/propertys/autoSavePropertyData
Content-Type: application/json

{
    "bathroomCount": 1,
    "category": "Luxury",
    "cityinfo": {
        "value": "Accra",
        "label": "Accra",
        "countryCode": "GH",
        "latlng": [
            "5.55602000",
            "-0.19690000"
        ],
        "latitude": "5.55602000",
        "longitude": "-0.19690000",
        "name": "Accra"
    },
    "description": "Fully Furnished Apartment",
    "guestCount": 4,
    "imageSrc": [],
    "localinfo": {
        "value": "AA",
        "label": "Greater Accra",
        "countryCode": "GH",
        "latlng": [
            "5.81428360",
            "0.07467670"
        ],
        "latitude": "5.81428360",
        "longitude": "0.07467670",
        "name": "Greater Accra",
        "isoCode": "AA"
    },
    "location": {
        "value": "GH",
        "label": "Ghana",
        "currency": "GHS",
        "phonecode": "233",
        "flag": "🇬🇭",
        "latlng": [
            8,
            -2
        ],
        "latitude": 8,
        "longitude": -2,
        "region": "Ghana",
        "isoCode": "GH",
        "name": "Ghana",
        "timezones": []
    },
    "price": "63.58",
    "roomCount": 2,
    "streetAddress": "Third Circular Road",
    "streetAddress2": null,
    "streetCity": "Accra",
    "streetZipCode": "GA-51042",
    "title": "Embassy Gardens",
    "town": null,
    "userId": 1
}



###


GET http://localhost:3334/api/propertys/all


###


GET http://localhost:3334/api/propertys/id/6



###


GET http://localhost:3334/api/propertys/uuid/18d206d4-9faf-45f3-b63b-9154461a30a8

###


POST http://localhost:3334/api/propertys/deleteProperty/uuid/49510f6a-f37f-483a-a673-5a6fc807e05e
Content-Type: application/json

{
    "uuid": "e8e448c2-5f43-47f3-a4a3-85ad854c93e6",
    "userId": 2,
    "propertyId": 2
}