import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import NavbarPublic from "@/Components/navbar/NavbarPublic";
import ClientOnly from "@/Components/ClientOnly";
import RegisterModal from "@/Components/modals/auth/RegisterModal";
import LoginModal from "@/Components/modals/auth/LoginModal";
import ToasterProvider from "@/Providers/ToasterProvider";
import getCurrentUser from "@/Actions/getCurrentUser";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const currentUser = await getCurrentUser();

  console.log('currentUser on Layout: ', currentUser)


  return (
    <html lang="en">
      <body className={inter.className}>
        <ClientOnly>
              <ToasterProvider />
              <RegisterModal />
              <LoginModal />
              <NavbarPublic currentUser={currentUser as any} />

              {children}

        </ClientOnly>
      </body>
    </html>
  );
}
